package com.gamingbacklog.api.gamingbacklogapi.models.enums

enum class Platforms(val displayName: String) {
    PlayStation_VR2("PlayStation VR2"),
    Meta_Quest_3("Meta Quest 3"),
    Atari_2600("Atari 2600"),
    Mac("Mac"),
    Evercade("Evercade"),
    Android("Android"),
    Playdate("Playdate"),
    Oculus_Quest("Oculus Quest"),
    PC_Windows("PC (Microsoft Windows)"),
    Meta_Quest_2("Meta Quest 2"),
    PlayStation_5("PlayStation 5"),
    Xbox_Series_X_S("Xbox Series X|S"),
    Xbox_One("Xbox One"),
    LeapTV("LeapTV"),
    Oculus_Rift("Oculus Rift"),
    Nintendo_Switch("Nintendo Switch"),
    Gear_VR("Gear VR"),
    PlayStation_VR("PlayStation VR"),
    Arduboy("Arduboy"),
    PlayStation_4("PlayStation 4"),
    Windows_Phone("Windows Phone"),
    Oculus_Go("Oculus Go"),
    PlayStation_Vita("PlayStation Vita"),
    New_Nintendo_3DS("New Nintendo 3DS"),
    Wii("Wii"),
    Ouya("Ouya"),
    PlayStation_3("PlayStation 3"),
    Wii_U("Wii U"),
    Nintendo_3DS("Nintendo 3DS"),
    PlayStation_Portable("PlayStation Portable"),
    Leapster_Explorer_LeadPad_Explorer("Leapster Explorer/LeadPad Explorer"),
    Nintendo_DSi("Nintendo DSi"),
    Nintendo_DS("Nintendo DS"),
    Xbox_360("Xbox 360"),
    Zeebo("Zeebo"),
    Arcade("Arcade"),
    Windows_Mobile("Windows Mobile"),
    iOS("iOS"),
    Legacy_Mobile_Device("Legacy Mobile Device"),
    HyperScan("HyperScan"),
    Blu_ray_Player("Blu-ray Player"),
    V_Smile("V.Smile"),
    PlayStation_2("PlayStation 2"),
    N_Gage("N-Gage"),
    Game_Boy_Advance("Game Boy Advance"),
    Tapwave_Zodiac("Tapwave Zodiac"),
    Leapster("Leapster"),
    Nintendo_64("Nintendo 64"),
    WonderSwan_Color("WonderSwan Color"),
    WonderSwan("WonderSwan"),
    Xbox("Xbox"),
    Pokémon_mini("Pokémon mini"),
    Nintendo_GameCube("Nintendo GameCube"),
    Nuon("Nuon"),
    PlayStation("PlayStation"),
    Visual_Memory_Unit_Visual_Memory_System("Visual Memory Unit / Visual Memory System"),
    PocketStation("PocketStation"),
    Nintendo_64DD("Nintendo 64DD"),
    Dreamcast("Dreamcast"),
    Neo_Geo_Pocket_Color("Neo Geo Pocket Color"),
    DVD_Player("DVD Player"),
    BlackBerry_OS("BlackBerry OS"),
    Sega_Mega_Drive_Genesis("Sega Mega Drive/Genesis"),
    Game_Boy_Color("Game Boy Color"),
    Super_Nintendo_Entertainment_System("Super Nintendo Entertainment System"),
    Game_Boy("Game Boy"),
    Neo_Geo_Pocket("Neo Geo Pocket"),
    Game_com("Game.com"),
    Super_Famicom("Super Famicom"),
    Satellaview("Satellaview"),
    Hyper_Neo_Geo_64("Hyper Neo Geo 64"),
    Palm_OS("Palm OS"),
    Sega_Saturn("Sega Saturn"),
    Sega_Pico("Sega Pico"),
    Atari_Jaguar_CD("Atari Jaguar CD"),
    Casio_Loopy("Casio Loopy"),
    Sega_32X("Sega 32X"),
    Virtual_Boy("Virtual Boy"),
    Neo_Geo_CD("Neo Geo CD"),
    Sega_Master_System_Mark_III("Sega Master System/Mark III"),
    Playdia("Playdia"),
    _3DO_Interactive_Multiplayer("3DO Interactive Multiplayer"),
    PC_FX("PC-FX"),
    Amiga_CD32("Amiga CD32"),
    Mega_Duck_Cougar_Boy("Mega Duck/Cougar Boy"),
    Nintendo_Entertainment_System("Nintendo Entertainment System"),
    Sega_CD("Sega CD"),
    Atari_Jaguar("Atari Jaguar"),
    Family_Computer("Family Computer"),
    Watara_QuickShot_Supervision("Watara/QuickShot Supervision"),
    Sega_Game_Gear("Sega Game Gear"),
    Philips_CD_i("Philips CD-i"),
    Amiga("Amiga"),
    Neo_Geo_AES("Neo Geo AES"),
    Turbografx_16_PC_Engine_CD("Turbografx-16/PC Engine CD"),
    Linux("Linux"),
    Atari_Lynx("Atari Lynx"),
    Neo_Geo_MVS("Neo Geo MVS"),
    Commodore_CDTV("Commodore CDTV"),
    BBC_Microcomputer_System("BBC Microcomputer System"),
    Gamate("Gamate"),
    TurboGrafx_16_PC_Engine("TurboGrafx-16/PC Engine"),
    FM_Towns("FM Towns"),
    Apple_IIGS("Apple IIGS"),
    PC_9800_Series("PC-9800 Series"),
    PC_Engine_SuperGrafx("PC Engine SuperGrafx"),
    Acorn_Archimedes("Acorn Archimedes"),
    Sharp_X1("Sharp X1"),
    Sharp_X68000("Sharp X68000"),
    Commodore_C64_128_MAX("Commodore C64/128/MAX"),
    Family_Computer_Disk_System("Family Computer Disk System"),
    Amstrad_PCW("Amstrad PCW"),
    Amstrad_CPC("Amstrad CPC"),
    Acorn_Electron("Acorn Electron"),
    Dragon_32_64("Dragon 32/64"),
    Tatung_Einstein("Tatung Einstein"),
    Atari_ST_STE("Atari ST/STE"),
    Epoch_Super_Cassette_Vision("Epoch Super Cassette Vision"),
    Sinclair_QL("Sinclair QL"),
    Commodore_16("Commodore 16"),
    Atari_5200("Atari 5200"),
    Atari_7800("Atari 7800"),
    HP_3000("HP 3000"),
    Thomson_MO5("Thomson MO5"),
    MSX2("MSX2"),
    MSX("MSX"),
    Sharp_MZ_2200("Sharp MZ-2200"),
    Vectrex("Vectrex"),
    Commodore_Plus_4("Commodore Plus/4"),
    SG_1000("SG-1000"),
    NEC_PC_6000_Series("NEC PC-6000 Series"),
    ZX_Spectrum("ZX Spectrum"),
    Intellivision("Intellivision"),
    ColecoVision("ColecoVision"),
    FM_7("FM-7"),
    Commodore_VIC_20("Commodore VIC-20"),
    TRS_80("TRS-80"),
    Texas_Instruments_TI_99("Texas Instruments TI-99"),
    Sinclair_ZX81("Sinclair ZX81"),
    PC_8800_Series("PC-8800 Series"),
    Epoch_Cassette_Vision("Epoch Cassette Vision"),
    DOS("DOS"),
    Atari_8_bit("Atari 8-bit"),
    Game_Watch("Game & Watch"),
    TRS_80_Color_Computer("TRS-80 Color Computer"),
    Microvision("Microvision"),
    Odyssey_2_Videopac_G7000("Odyssey 2 / Videopac G7000"),
    _1292_Advanced_Programmable_Video_System("1292 Advanced Programmable Video System"),
    Exidy_Sorcerer("Exidy Sorcerer"),
    PC_50X_Family("PC-50X Family"),
    Apple_II("Apple II"),
    VC_4000("VC 4000"),
    AY_3_8500("AY-3-8500"),
    Commodore_PET("Commodore PET"),
    Bally_Astrocade("Bally Astrocade"),
    AY_3_8760("AY-3-8760"),
    AY_3_8710("AY-3-8710"),
    AY_3_8603("AY-3-8603"),
    Fairchild_Channel_F("Fairchild Channel F"),
    AY_3_8610("AY-3-8610"),
    AY_3_8607("AY-3-8607"),
    AY_3_8605("AY-3-8605"),
    AY_3_8606("AY-3-8606"),
    Sol_20("Sol-20"),
    Odyssey("Odyssey"),
    PLATO("PLATO"),
    CDC_Cyber_70("CDC Cyber 70"),
    PDP_10("PDP-10"),
    HP_2100("HP 2100"),
    SDS_Sigma_7("SDS Sigma 7"),
    PDP_11("PDP-11"),
    Call_A_Computer_time_shared_mainframe_computer_system("Call-A-Computer time-shared mainframe computer system"),
    PDP_8("PDP-8"),
    PDP_1("PDP-1"),
    Nintendo_PlayStation("Nintendo PlayStation"),
    Donner_Model_30("Donner Model 30"),
    EDSAC("EDSAC"),
    Ferranti_Nimrod_Computer("Ferranti Nimrod Computer"),
    Intellivision_Amico("Intellivision Amico"),
    Legacy_Computer("Legacy Computer"),
    Handheld_Electronic_LCD("Handheld Electronic LCD"),
    SwanCrystal("SwanCrystal");

    override fun toString(): String {
        return displayName
    }
}
